from PyQt5 import QtCore, QtGui, QtWidgets
import Experiment4.improved_euler
import Experiment4.runge_kutta
from Experiment3 import  romberg,bbctx
from Experiment2 import lagrange,newton
from Experiment1 import  doolittle,guess
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(571, 422)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 551, 351))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.doolittle = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.doolittle.setObjectName("doolittle")
        self.gridLayout.addWidget(self.doolittle, 2, 0, 1, 1)
        self.guass = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.guass.setObjectName("guass")
        self.gridLayout.addWidget(self.guass, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.newton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.newton.setObjectName("newton")
        self.gridLayout_2.addWidget(self.newton, 2, 0, 1, 1)
        self.lagrange = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.lagrange.setObjectName("lagrange")
        self.gridLayout_2.addWidget(self.lagrange, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.romberge = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.romberge.setObjectName("romberge")
        self.gridLayout_5.addWidget(self.romberge, 2, 0, 1, 1)
        self.bbctx = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.bbctx.setObjectName("bbctx")
        self.gridLayout_5.addWidget(self.bbctx, 1, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_5)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.runge_kutta = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.runge_kutta.setObjectName("runge_kutta")
        self.gridLayout_4.addWidget(self.runge_kutta, 2, 0, 1, 1)
        self.improved_euler = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.improved_euler.setObjectName("improved_euler")
        self.gridLayout_4.addWidget(self.improved_euler, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 571, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.guass_window = guess.Ui_Dialog()
        self.guass.clicked.connect(self.guass_window.window.show)
        self.doolittle_window = doolittle.Ui_Dialog()
        self.doolittle.clicked.connect(self.doolittle_window.window.show)

        self.lagrange_window = lagrange.Ui_Dialog()
        self.lagrange.clicked.connect(self.lagrange_window.window.show)
        self.newton_window = newton.Ui_Dialog()
        self.newton.clicked.connect(self.newton_window.window.show)

        self.bbctx_window = bbctx.Ui_Dialog()
        self.bbctx.clicked.connect(self.bbctx_window.window.show)
        self.romberge_window = romberg.Ui_Dialog()
        self.romberge.clicked.connect(self.romberge_window.window.show)

        self.runge_kutta_window = Experiment4.runge_kutta.Runge_kutta()
        self.runge_kutta.clicked.connect(self.runge_kutta_window.window.show)
        self.improved_euler_window = Experiment4.improved_euler.Improved_euler()
        self.improved_euler.clicked.connect(self.improved_euler_window.window.show)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "数值计算实验"))
        self.label.setText(_translate("MainWindow", "实验一 直接法解线性方程组"))
        self.doolittle.setText(_translate("MainWindow", "Doolittle 三角分解法"))
        self.guass.setText(_translate("MainWindow", "Guass 列选主元消去法"))
        self.label_2.setText(_translate("MainWindow", "实验二 插值方法"))
        self.newton.setText(_translate("MainWindow", "牛顿插值法"))
        self.lagrange.setText(_translate("MainWindow", "拉格郎日插值法"))
        self.label_4.setText(_translate("MainWindow", "实验三 数值积分"))
        self.romberge.setText(_translate("MainWindow", "龙贝格法"))
        self.bbctx.setText(_translate("MainWindow", "变步长梯形法"))
        self.label_3.setText(_translate("MainWindow", "实验四 常微分方程的数值解"))
        self.runge_kutta.setText(_translate("MainWindow", "四阶龙格-库塔法"))
        self.improved_euler.setText(_translate("MainWindow", "改进欧拉法"))


if __name__ == '__main__':
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
